name: Deploy documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up toolchain
        uses: moonrepo/setup-toolchain@v0.6.4
        with:
          auto-install: true
          moon-version: 2.5.3
          proto-version: 0.61.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build documentation
        run: moon run docs:build

      - name: Configure Pages
        uses: actions/configure-pages@v6.0.0

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: docs/.vitepress/dist

  deploy:
    name: Deploy documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      id-token: write
      pages: write

    steps:
      - name: Deploy Pages artifact
        id: deployment
        uses: actions/deploy-pages@v5.0.0
